[workspace]
resolver = "2"
members = [ "liberated-chat-frontend","liberated-chat-server", "liberated-chat-shuttle"]

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"
strip = "symbols"